#!/usr/bin/env python

import os
import time
import random
import sys
import mimetypes

from pprint import pprint # Pretty printing.

class Hollyscroll(object):
    current_file = ''
    """Currently displayed file"""

    filelist = []
    """List of files to render"""

    mode = 'print'
    """Mode of operation: print or hex"""

    modes = ['print', 'hex']

    pause_time = 1
    """Time in seconds between line prints"""

    def __init__(self, filelist):
        """Constructor"""
        self.filelist = []

        print "Reading file list"
        for filename in filelist:
            if os.path.isdir(filename):
                self.populate_filelist(filename)
            else:
                self.filelist.append(filename)

        print "{0} files to display".format(len(self.filelist))

        self.generate_pausetime()

    def populate_filelist(self, path):
        """Populate the filelist by recursing a path"""
        for root,dirs,files in os.walk(path):
            # modify "dirs" in place to prevent
            # future code in os.walk from seeing those
            # that start with "."
            dirs[:] = [d for d in dirs if not d.startswith('.')]

            if len(files) == 0:
                continue

            for filename in files:
                if filename.startswith('.'):
                    continue
                self.filelist.append(root + '/' + filename)

    def execute(self):
        """Run the scroller"""
        self.display_file_data()

    def generate_pausetime(self):
        """Set the pause time controlling the scroll speed"""
        self.pause_time = random.random()

    def next_mode(self):
        try:
            mode_index = self.modes.index(self.mode)
            mode_index = mode_index + 1
        except ValueError as error:
            mode_index = 0

        if mode_index >= len(self.modes):
            mode_index = 0

        self.mode = self.modes[mode_index]

    def display_file_data(self):
        hollytypes = HollyTypes()

        for filename in self.filelist:
            self.generate_pausetime()
            filename = os.path.realpath(filename)
            self.current_file = filename
            self.next_mode()

            if os.path.isdir(filename):
                continue

            mimetype = mimetypes.guess_type(filename)[0]

            # Get the file extension
            # (splitext returns filename,extension)
            fileExtension = os.path.splitext(filename)[1]

            # Default to hex mode
            self.mode = 'hex'

            # print_types or print_extensions will force the mode to print
            if hollytypes.is_print_type(mimetype, fileExtension):
                self.mode = 'print'

            try:
                if self.mode == 'print':
                    lines = self.read_file_data_print(filename)
                else:
                    # last ditch effort to determine if file should be in print
                    # mode
                    first_line = self.read_first_line(filename)
                    if (first_line[:2] == '#!'):
                        # shebang found, switch to print mode
                        self.mode = 'print'
                        lines = self.read_file_data_print(filename)
                    else:
                        lines = self.read_file_data_hex(filename)
            except:
                continue

            print '### [' + filename + ' ' + str(mimetype) + '] ### ' + self.mode
            for line in lines:
                print line,
                time.sleep(self.pause_time)

    def read_first_line(self, filename):
        """Read the first line of a file"""
        file_data = open(filename)
        return file_data.readline()

    def read_file_data_print(self, filename):
        """Read in a file for print mode"""
        file_data = open(filename)
        return file_data.readlines()

    def read_file_data_hex(self, filename):
        """Read in a file for hex mode"""
        cmd = "xxd '" + filename + "' > /tmp/holly"
        os.system(cmd)
        file_data = open('/tmp/holly')
        return file_data.readlines()

class HollyTypes(object):
    print_types = [
        'application/json',
        'application/x-httpd-php',
        'application/xml',
    ]

    print_extensions = [
        '.aux',
        '.json',
        '.log',
        '.lua',
        '.md',
        '.php',
        '.yml',
    ]

    def is_print_type(self, mimetype, extension):
        if mimetype != None and mimetype in self.print_types \
            or extension in self.print_extensions:
                return True

        if mimetype != None and mimetype[:4] == 'text':
            return True

        return False

def select_path(path):
    realpaths = []
    for item in path:
        if not os.path.exists(item):
            sys.stderr.write("Warning: path '{0}' not found.\n".format(item))
            continue
        realpaths.append(os.path.realpath(item))

    return realpaths

if __name__ == "__main__":
    # By default hollyscroll will use the current directory
    path = ['.']

    # Check arguments. User can specify a list of arguments as files or
    # directories to read and scroll.
    if len(sys.argv) > 1:
        sys.argv.pop(0)
        path = select_path(sys.argv)

    hollyscroll = Hollyscroll(path)

    try:
        hollyscroll.execute()
    except KeyboardInterrupt as error:
        print '---'

    sys.exit(0)
